version: "3"
services:
  jenkins:
    container_name: service.jenkins
    image: jenkinsci/blueocean
    user: root
    volumes:
       - jenkins-data:/var/jenkins_home
       - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - "50000:50000"
      - "8080:8080"
volumes:
  jenkins-data: